aa_standalone(...
    '/home/ta02/GitHub/automaticanalysis/aa_recipes_and_parametersets/aap_parameters_defaults_CBSU.xml',...
    '/home/ta02/GitHub/aa/test/BIDS114_tasklist.xml',...
    '/home/ta02/GitHub/aa/test/BIDS114_test1_aa.xml',...
    'mridatadir','/imaging/ta02/Temp/BIDS/ds114_test1',...
    'anadir','/imaging/ta02/aa/standalone/BIDS114/aa_test1',...
    'subj','01')

aa_standalone(...
    '/home/ta02/GitHub/automaticanalysis/aa_recipes_and_parametersets/aap_parameters_defaults_CBSU.xml',...
    '/home/ta02/GitHub/aa/test/BIDS114_tasklist.xml',...
    '/home/ta02/GitHub/aa/test/BIDS114_test2_aa.xml',...
    'mridatadir','/imaging/ta02/Temp/BIDS/ds114_test2',...
    'anadir','/imaging/ta02/aa/standalone/BIDS114/aa_test2',...
    'subj','01')