aa_standalone(...
    '/imaging/ta02/aa/standalone/BIDS114/aap_parameters_defaults_CBSU.xml',...
    '/imaging/ta02/aa/standalone/BIDS114/BIDS114_tasklist.xml',...
    '/imaging/ta02/aa/standalone/BIDS114/BIDS114_aa.m',...
    'mridatadir','/imaging/ta02/Temp/BIDS/ds114_test2',...
    'anadir','/imaging/ta02/aa/standalone/BIDS114/aa_test2',...
    'subj','02')