aa_standalone(...
    '/MRIWork/MRIWork09/ta/tibor_auer/programs/automaticanalysis/aa_recipes_and_parametersets/aap_parameters_defaults_RHUL.xml',...
    'mridatadir','/MRIWork/MRIWork09/ta/tibor_auer/data/BIDS/ds114_test1',...
    'anadir','/MRIWork/MRIWork09/ta/tibor_auer/aa/BIDS-App/aa_test1',...
    'subj','01',...
    '/MRIWork/MRIWork09/ta/tibor_auer/aa/BIDS-App/test/BIDS114_tasklist.xml',...
    '/MRIWork/MRIWork09/ta/tibor_auer/aa/BIDS-App/test/BIDS114_test1_aa.xml')

aa_standalone(...
    '/MRIWork/MRIWork09/ta/tibor_auer/programs/automaticanalysis/aa_recipes_and_parametersets/aap_parameters_defaults_RHUL.xml',...
    'mridatadir','/MRIWork/MRIWork09/ta/tibor_auer/data/BIDS/ds114_test2',...
    'anadir','/MRIWork/MRIWork09/ta/tibor_auer/aa/BIDS-App/aa_test2',...
    'subj','01',...
    '/MRIWork/MRIWork09/ta/tibor_auer/aa/BIDS-App/test/BIDS114_tasklist.xml',...
    '/MRIWork/MRIWork09/ta/tibor_auer/aa/BIDS-App/test/BIDS114_test2_aa.xml')
