% CBSU
aa_standalone(...
    '/home/ta02/GitHub/automaticanalysis/aa_recipes_and_parametersets/aap_parameters_defaults_CBSU.xml',...
    '/home/ta02/GitHub/aa/test/BIDS114_tasklist.xml',...
    '/home/ta02/GitHub/aa/test/BIDS114_test1_aa.xml',...
    'mridatadir','/imaging/ta02/data/BIDS/ds114_test1',...
    'anadir','/imaging/ta02/aa/standalone/aa_test1',...
    'subj','sub-01'...
    )
