general:
  artifacts:
    - "~/outputs_basic1"
    - "~/outputs_basic2"
    - "~/outputs_advanced1"
    - "~/outputs_advanced2"
machine:
  services:
    - docker

dependencies:
  cache_directories:
    - "~/docker"
    - "~/data"

  override:
    - mkdir ${HOME}/Download
    - if [[ ! -d ~/data/ds114_test1 ]]; then wget -c -O ${HOME}/Download/ds114_test1.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e54a326c613b01d7d3ed90" && mkdir -p ${HOME}/data && tar xf ${HOME}/Download/ds114_test1.tar -C ${HOME}/data; fi
    - if [[ ! -d ~/data/ds114_test2 ]]; then wget -c -O ${HOME}/Download/ds114_test2.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549f9b83f6901d457d162" && mkdir -p ${HOME}/data && tar xf ${HOME}/Download/ds114_test2.tar -C ${HOME}/data; fi
    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
    - git describe --tags --always > version
    - docker build -t bids/${CIRCLE_PROJECT_REPONAME} . :
        timeout: 86400
    - mkdir -p ~/docker; docker save "bids/${CIRCLE_PROJECT_REPONAME}" > ~/docker/image.tar
    - mkdir -p ${HOME}/outputs
    - echo "cHJpbnRmICJ0aWJvci5hdWVyQGdtYWlsLmNvbVxuNzA2MVxuICpDY3BpNng3UEFJZVFcbiBGUzk2cFBLNXZXLjBnXG4iID4gJHtIT01FfS9Eb3dubG9hZC9saWNlbnNlLnR4dAo=" | base64 -d | sh

test:
  override:
    # Print version
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset bids/${CIRCLE_PROJECT_REPONAME,,} --version

    # Basic use case (default pipeline - structural and task-based functional only)
    # participant level tests for single session dataset
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs_basic1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 01 :
        timeout: 86400
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs_basic1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 02 :
        timeout: 86400
    # group level test for single session dataset
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs_basic1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs group :
        timeout: 86400
    # participant level tests for a longitudinal dataset
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs_basic2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 01 :
        timeout: 86400
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs_basic2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 02 :
        timeout: 86400
    # group level test for a longitudinal dataset
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs_basic2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs group :
        timeout: 86400

    # Advanced use case (configured pipeline)
    # participant level tests for single session dataset
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/Download:/download -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs_advanced1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 01 --freesurfer_license /download/license.txt /opt/test/BIDS114_tasklist.xml /opt/test/BIDS114_test1_aa.xml :
        timeout: 86400
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/Download:/download -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs_advanced1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 02 --freesurfer_license /download/license.txt /opt/test/BIDS114_tasklist.xml /opt/test/BIDS114_test1_aa.xml :
        timeout: 86400
    # group level test for single session dataset (two-step approach: 1. update aap, 2 run connection)
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/Download:/download -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs_advanced1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs group --freesurfer_license /download/license.txt /opt/test/BIDS114_group_tasklist.xml /opt/test/BIDS114_test1_group_aa.xml :
        timeout: 86400
    # participant level tests for a longitudinal dataset
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/Download:/download -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs_advanced2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 01 --freesurfer_license /download/license.txt /opt/test/BIDS114_tasklist.xml /opt/test/BIDS114_test2_aa.xml :
        timeout: 86400
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/Download:/download -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs_advanced2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 02 --freesurfer_license /download/license.txt /opt/test/BIDS114_tasklist.xml /opt/test/BIDS114_test2_aa.xml :
        timeout: 86400
    # group level test for a longitudinal dataset (two-step approach: 1. update aap, 2 run connection)
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/Download:/download -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs_advanced2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs group --freesurfer_license /download/license.txt /opt/test/BIDS114_group_tasklist.xml /opt/test/BIDS114_test2_group_aa.xml :
        timeout: 86400

deployment:
  hub:
    owner: BIDS-Apps
    tag: /.*/
    commands:
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker push bids/${CIRCLE_PROJECT_REPONAME}:latest; fi :
          timeout: 21600
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker tag bids/${CIRCLE_PROJECT_REPONAME} bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG && docker push bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG; fi :
          timeout: 21600
