---
version: 2.1

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2

    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache

    - run:
        name: 'Get test data: ds114_test1'
        command: |
          if [[ ! -d ~/data/ds114_test1 ]]; then
            wget -c -O ${HOME}/ds114_test1.tar "https://osf.io/download/zerfq/" && \
            mkdir -p ${HOME}/data && \
            tar xf ${HOME}/ds114_test1.tar -C ${HOME}/data;
          else
            echo "using data from cache"
          fi
    - run:
        name: 'Get test data: ds114_test2'
        command: |
          if [[ ! -d ~/data/ds114_test2 ]]; then
            wget -c -O ${HOME}/ds114_test2.tar "https://osf.io/download/eg4ma/" && \
            mkdir -p ${HOME}/data && \
            tar xf ${HOME}/ds114_test2.tar -C ${HOME}/data;
          else
            echo "using data from cache"
          fi

    - run:
        name: Build Docker image
        command: |
          if [[ -e ~/docker/image.tar ]]; then
            echo "loading image from cache"
            docker load -i ~/docker/image.tar;
          fi
          git describe --tags --always > version
          docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
          mkdir -p ${HOME}/docker
          docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
        no_output_timeout: 6h

    - run:
        name: freesurfer license
        command: |
          mkdir -p ${HOME}/Download/freesurfer
          echo "cHJpbnRmICJ0aWJvci5hdWVyQGdtYWlsLmNvbVxuNzA2MVxuICpDY3BpNng3UEFJZVFcbiBGUzk2cFBLNXZXLjBnXG4iID4gJHtIT01FfS9Eb3dubG9hZC9saWNlbnNlLnR4dAo=" | base64 -d | sh
          ls -l ${HOME}/Download/freesurfer
          ls -l
          
    - save_cache:
        key: my_cache
        paths:
        - ~/docker
        - ~/data

    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - data/ds114_test2
        - docker/image.tar
        - Download/freesurfer/license.txt

  test:
    machine:
      image: ubuntu-2204:2022.10.2

    parameters:
      dataset:
        type: string

    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        command: |
          docker load -i /tmp/workspace/docker/image.tar

    - run:
        name: Print version
        command: |
          docker run -ti --rm \
            -v ${HOME}/data/ds114_test<< parameters.dataset >>:/bids_dataset \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                --version

    - run: mkdir -p ${HOME}/outputs_basic<< parameters.dataset >>
    - run:
        name: Basic use case (default pipeline - structural and task-based functional only)
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_basic<< parameters.dataset >>:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label 01
        no_output_timeout: 6h
    - run:
        name: participant_label 02
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_basic<< parameters.dataset >>:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label 02
        no_output_timeout: 6h
    - run:
        name: group level
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_basic<< parameters.dataset >>:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs group
        no_output_timeout: 6h

  test_advanced:
    machine:
      image: ubuntu-2204:2022.10.2

    parameters:
      dataset:
        type: string

    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run:
        command: |
          docker load -i /tmp/workspace/docker/image.tar

    - run: mkdir -p ${HOME}/outputs_advanced<< parameters.dataset >>
    - run:
        name: Advanced use case (configured pipeline)
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/Download:/download \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_advanced<< parameters.dataset >>:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label 01 \
                --freesurfer_license /download/license.txt \
                /opt/test/BIDS114_tasklist.xml \
                /opt/test/BIDS114_test<< parameters.dataset >>_aa.xml
        no_output_timeout: 6h
    - run:
        name: participant_label 02
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/Download:/download \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_advanced<< parameters.dataset >>:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label 02 \
                --freesurfer_license /download/license.txt \
                /opt/test/BIDS114_tasklist.xml \
                /opt/test/BIDS114_test<< parameters.dataset >>_aa.xml
        no_output_timeout: 6h
    - run:
        name: 'group level test for single session dataset (two-step approach: 1. update aap, 2 run connection)'
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/Download:/download \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_advanced<< parameters.dataset >>:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs group --freesurfer_license \
                /download/license.txt \
                /opt/test/BIDS114_group_tasklist.xml \
                /opt/test/BIDS114_test<< parameters.dataset >>_group_aa.xml
        no_output_timeout: 6h

  deployment:
    docker:
    - image: circleci/buildpack-deps:stretch
    steps:
    - attach_workspace:
        at: /tmp/workspace

    - run: docker load -i /tmp/workspace/image.tar
    - run:
        name: push to dockerhub
        command: |
          if [[ -n "$DOCKER_PASS" ]]; then
            repo_name=`echo  ${CIRCLE_PROJECT_REPONAME} | tr '[:upper:]' '[:lower:]'`
            echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
            echo "Pushing to DockerHub bids/${repo_name}:unstable"
            docker tag bids/${repo_name} bids/${repo_name}:unstable
            docker push bids/${repo_name}:unstable
            if [[ -n "${CIRCLE_TAG}" ]]; then
              echo "Pushing to DockerHub bids/${repo_name}:${CIRCLE_TAG}"
              docker push bids/${repo_name}:latest
              docker tag bids/${repo_name} bids/${repo_name}:${CIRCLE_TAG}
              docker push bids/${repo_name}:${CIRCLE_TAG};
            fi
          else
            echo "No DOCKER_PASS, skipping push to DockerHub"
          fi

workflows:
  build-test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - test:
        requires:
        - build
        matrix:
          parameters:
            dataset: ['1', '2']
        filters:
          tags:
            only: /.*/
    - test_advanced:
        requires:
        - build
        matrix:
          parameters:
            dataset: ['1', '2']
        filters:
          tags:
            only: /.*/
    - deployment:
        requires:
        - test
        - test_advanced
        filters:
          tags:
            only: /.*/
# VS Code Extension Version: 1.5.1
