---
version: 2

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2

    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache

    - run:
        command: |
          if [[ ! -d ~/data/ds114_test1 ]]; then
            mkdir -p ${HOME}/data
            wget -c -O ${HOME}/ds114_test1.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e54a326c613b01d7d3ed90" && \
            tar xf ${HOME}/ds114_test1.tar -C ${HOME}/data;
          fi
    - run:
        command: |
          if [[ ! -d ~/data/ds114_test2 ]]; then
            wget -c -O ${HOME}/ds114_test2.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549f9b83f6901d457d162" && \
            mkdir -p ${HOME}/data && tar xf ${HOME}/ds114_test2.tar -C ${HOME}/data;
          fi

    - run:
        command: |
          if [[ -e ~/docker/image.tar ]]; then
            docker load -i ~/docker/image.tar;
            echo "loaded image";
          fi
    - run: git describe --tags --always > version
    - run:
        command: docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
        no_output_timeout: 6h
    - run: mkdir -p ~/docker; docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
    - run: mkdir -p ${HOME}/outputs
    - run: echo "cHJpbnRmICJ0aWJvci5hdWVyQGdtYWlsLmNvbVxuNzA2MVxuICpDY3BpNng3UEFJZVFcbiBGUzk2cFBLNXZXLjBnXG4iID4gJHtIT01FfS9Eb3dubG9hZC9saWNlbnNlLnR4dAo="
        | base64 -d | sh

    - save_cache:
        key: my_cache
        paths:
        - ~/docker
        - ~/data

  test:
    machine:
      image: ubuntu-2204:2022.10.2

    steps:
    - attach_workspace:
        at: /tmp/workspace

        # Print version
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/data/ds114_test1:/bids_dataset bids/${CIRCLE_PROJECT_REPONAME,,} --version

        # Basic use case (default pipeline - structural and task-based functional only)
        # participant level tests for single session dataset
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs_basic1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs participant --participant_label 01
        no_output_timeout: 6h
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs_basic1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs participant --participant_label 02
        no_output_timeout: 6h
        # group level test for single session dataset
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs_basic1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs group
        no_output_timeout: 6h
        # participant level tests for a longitudinal dataset
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs_basic2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs participant --participant_label 01
        no_output_timeout: 6h
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v
             ${HOME}/data/ds114_test2:/bids_dataset -v
             ${HOME}/outputs_basic2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,}
             /bids_dataset /outputs participant --participant_label 02
        no_output_timeout: 6h
        # group level test for a longitudinal dataset
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs_basic2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs group
        no_output_timeout: 6h

        # Advanced use case (configured pipeline)
        # participant level tests for single session dataset
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/Download:/download \
              -v ${HOME}/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs_advanced1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs participant --participant_label 01 --freesurfer_license /download/license.txt \
              /opt/test/BIDS114_tasklist.xml \
              /opt/test/BIDS114_test1_aa.xml
        no_output_timeout: 6h
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/Download:/download \
              -v ${HOME}/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs_advanced1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs participant --participant_label 02 --freesurfer_license /download/license.txt \
              /opt/test/BIDS114_tasklist.xml \
              /opt/test/BIDS114_test1_aa.xml
        no_output_timeout: 6h
        # group level test for single session dataset (two-step approach: 1. update aap, 2 run connection)
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/Download:/download \
              -v ${HOME}/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs_advanced1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs group --freesurfer_license /download/license.txt \
              /opt/test/BIDS114_group_tasklist.xml \
              /opt/test/BIDS114_test1_group_aa.xml
        no_output_timeout: 6h
        # participant level tests for a longitudinal dataset
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/Download:/download \
              -v ${HOME}/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs_advanced2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs participant --participant_label 01 --freesurfer_license /download/license.txt \
              /opt/test/BIDS114_tasklist.xml \
              /opt/test/BIDS114_test2_aa.xml
        no_output_timeout: 6h
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/Download:/download \
              -v ${HOME}/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs_advanced2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs participant --participant_label 02 --freesurfer_license /download/license.txt \
              /opt/test/BIDS114_tasklist.xml \
              /opt/test/BIDS114_test2_aa.xml
        no_output_timeout: 6h
        # group level test for a longitudinal dataset (two-step approach: 1. update aap, 2 run connection)
    - run:
        command: |
          docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp \
              -v ${HOME}/Download:/download \
              -v ${HOME}/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs_advanced2:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} \
              /bids_dataset /outputs group --freesurfer_license /download/license.txt \
              /opt/test/BIDS114_group_tasklist.xml \
              /opt/test/BIDS114_test2_group_aa.xml :
        no_output_timeout: 6h

  deployment:
    docker:
    - image: circleci/buildpack-deps:stretch
    steps:
    - attach_workspace:
        at: /tmp/workspace

    - run: docker load -i /tmp/workspace/image.tar
    - run:
        command: |
          if [[ -n "$DOCKER_PASS" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS && \
              docker push bids/${CIRCLE_PROJECT_REPONAME,,}:latest;
          fi
        no_output_timeout: 6h
    - run:
        command: if [[ -n "$DOCKER_PASS" ]]; then docker login -u $DOCKER_USER -p $DOCKER_PASS && \ docker tag bids/${CIRCLE_PROJECT_REPONAME,,} bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG
          && \ docker push bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG; fi
        no_output_timeout: 6h

workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - test:
        requires:
        - build
        filters:
          tags:
            only: /.*/
    - deployment:
        requires:
        - build
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/
# VS Code Extension Version: 1.5.1
